# Generated by Django 4.1 on 2023-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donation_donator'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
