# Generated by Django 4.1 on 2023-07-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=False, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
