# Generated by Django 4.1 on 2023-07-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_contact_alter_user_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(default='-', max_length=13, null=True),
        ),
    ]
